# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='message',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='status',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 21, 11, 29, 652172, tzinfo=utc)),
        ),
    ]
