# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_status', '0004_auto_20171007_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 11, 38, 35, 945439, tzinfo=utc)),
        ),
    ]
