# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_status', '0005_auto_20171007_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
