# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_status', '0006_auto_20171007_1839'),
        ('app_home_status', '0002_auto_20171010_1318'),
    ]

    operations = [
    ]
