# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_status', '0007_merge_20171010_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
