# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_status', '0008_auto_20171011_1757'),
        ('app_home_status', '0008_auto_20171010_1553'),
    ]

    operations = [
    ]
