# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_status', '0009_merge_20171011_2343'),
        ('app_home_status', '0009_merge_20171011_2342'),
    ]

    operations = [
    ]
