# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_status', '0011_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_home_status.Status'),
        ),
    ]
