# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_status', '0012_comments_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='post',
        ),
    ]
